---

- hosts: all_servers
  become: yes
  roles:
    - name: vm_config

- hosts: slurmserver
  become: yes
  tags: slurm
  roles:
    - name: slurm
      slurm_type_of_node: 'front'

- hosts: slurmworker
  become: yes
  tags: slurm
  roles:
    - name: slurm
      slurm_type_of_node: 'wn'
  post_tasks:
    - name: Test network connectivity
      include_role:
        name: conn_test
      tags:
        - slurm
        - conn_test
