---

  - service: name=firewalld state=stopped
    when: ansible_distribution_major_version|int >= 7
    ignore_errors: yes

  - name: Include slurm config recipe
    include: "config_file.yaml"

  - name: Start Slurm Daemon in worker node
    service:
      name: slurmd
      enabled: yes
      state: restarted

  - name: Ensure slurmctld is not running in worker node
    service:
      name: slurmctld
      enabled: no
      state: stopped

  - name: Reconfigure SLURM
    command: scontrol reconfigure

  - name: allow the slurm user to acces the slurm logs
    file: path={{ slurmd_log }} mode=0644
