---
# SLURM version to install (in case of RH systems)
slurm_version: 19.05.5
# Flag to download remote RPMs
download_remote_rpms: true
rpm_base_url: http://gws-access.jasmin.ac.uk/public/cedaproc/rpms/
# Type of node to install: front or wn
slurm_type_of_node: front
# Name of the SLURM server
slurm_server_name: slurmserver
# IP address of the SLURM server
slurm_server_ip: 127.0.0.1
# List of the name of the WNs
slurm_wn_nodenames: []
# Number of CPUs of the WNs
slurm_wn_cpus: 1
# Default user for ssh and slurm management
slurm_user: slurm
slurm_user_id: 5001
# Templates files
templates: ""
# Number of Maximun nodes
max_number_of_nodes: 3
# Max job run time
max_run_time: INFINITE
# Slurm log file locations
slurmctld_log: /var/log/slurm/slurmctld.log
slurmd_log: /var/log/slurm/slurmd.log
